# Name of your site. Used to uniquely configure containers.
service: zimzcore_index

# Name of the container image.
image: syddaps/zimzcore_index

# Deploy to these servers.
servers:
  - 91.99.172.86

proxy:
  ssl: true
  host: zimzcore.com
  healthcheck:
    path: /up.html

# Use GIT_URL from env to auto-update site via git pulls.
# Remember to run `kamal env push` after making changes!
env:
  secret:
    - GIT_URL

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: syddaps

  # Always use an access token rather than real password when possible.
  password:
    - SKIFF_REGISTRY_PASSWORD

builder:
  arch: amd64

# Use a different ssh user than root
ssh:
  user: syd
